version: '3.8'
services:
  api:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.optimized
      args:
        BUILDKIT_INLINE_CACHE=1
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src:ro
    environment:
      - PYTHONUNBUFFERED=1
      - QDRANT_URL=http://qdrant:6333
      - MONGO_URI=mongodb://admin:password@mongodb:27017
      - MONGO_DB_NAME=Users
      - MONGO_USER_COLLECTION=user
      - MONGO_QUIZ_COLLECTION=quiz_sessions
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET_KEY=dev-secret-key
    env_file:
      - ../.env
    depends_on:
      - qdrant
      - mongodb
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_storage:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

volumes:
  qdrant_storage:
  mongodb_data: 